In [4]:
import pandas as pd

pd.set_option("display.max_rows", 999)
pd.set_option("display.max_columns", 999)
pd.set_option('display.max_rows', 999)
pd.set_option('display.min_rows', 999)

%config IPCompleter.use_jedi = False

In [5]:
df = pd.read_csv("/Users/dave/src/CSE6242/Data/apm_demo_faru_grad.csv")

In [7]:
display(df.head())
display(df.shape)

,Unnamed: 0,bedscode,year,cohortyr,cohortcount,apmcount,apmp,subgroup_apm,district_apm,num_asian,num_black,num_hisp,num_am_ind,num_white,num_female,num_male,num_lep,num_free_lunch,num_reduced_lunch,num_multi,num_swd,num_ecdis,num_ell,districtfaru,ufb,staid,star,totstat,lrev,fedrev,totrev,state_aid_total_revenues,star_total_revenues,state_revenues_total_revenues,bded,cadm,tsal,pps,cds,boc,tui1,tui2,ois,oiexp,cser,opmt,tchr,heal,oeb,total_fringe_benefits,ound,oth,subtot,trans,dsp,dsi,texp,total_unexpended_surplus_funds_t,revenue_expenditures,var,dcaadm,rev_pupil,exp_pupil,av_twpu,inc_twpu,pwr,apwr,cwr,instructional_salaries,instructional_fringe_benefits,ins_fb,adjusted_expenditures__subtotal,ie1,ie1_total,ie2_instructional_expenditures_i,ie2,ie3_instructional_expenditures_i,ie3_adj_exp,loc_eff_rate,district_cd,cohortye,total,gr_droppedout,gr_graduated,gr_iep,gr_ged,gr_stillenrolled,outcome_yrs,srcyear,subgroup_grad,_name_,gr_local_cnt
0,0,10100,2009,2006,703,106.0,15.078236,1,10100.0,463.0,4834.0,946.0,44.0,1687.0,NaN,NaN,502.0,4015.0,676.0,5.0,NaN,NaN,NaN,10100.0,21418880.0,83680866.0,9285758.0,92966624.0,109899299.0,21809847.0,224675770.0,0.372452,0.041330,0.413781,400060.0,2066613.0,58943059.0,6310445.0,4771588.0,5478167.0,104636.0,8201820.0,17248933.0,36382684.0,361152.0,10917401.0,4012540.0,18984955.0,12591807.0,35589302.0,3202637.0,2416650.0,192395147.0,6389009.0,9137435.0,7631707.0,215553298.0,0.099367,9122472.0,0.042321,10929.0,20557.761003,19723.057736,370462.0,114589.0,0.696095,0.694479,0.695287,92752192.0,3.301978e+07,0.153186,190573861.0,137441332.0,0.637621,1.704611e+08,0.790807,1.703565e+08,0.893913,21.01,10100.0,2004.0,677.0,122.0,453.0,41.0,7.0,54.0,5.0,200906.0,1.0,NaN,NaN
1,1,10100,2009,2006,703,106.0,15.078236,1,10100.0,463.0,4834.0,946.0,44.0,1687.0,NaN,NaN,502.0,4015.0,676.0,5.0,NaN,NaN,NaN,10100.0,21418880.0,83680866.0,9285758.0,92966624.0,109899299.0,21809847.0,224675770.0,0.372452,0.041330,0.413781,400060.0,2066613.0,58943059.0,6310445.0,4771588.0,5478167.0,104636.0,8201820.0,17248933.0,36382684.0,361152.0,10917401.0,4012540.0,18984955.0,12591807.0,35589302.0,3202637.0,2416650.0,192395147.0,6389009.0,9137435.0,7631707.0,215553298.0,0.099367,9122472.0,0.042321,10929.0,20557.761003,19723.057736,370462.0,114589.0,0.696095,0.694479,0.695287,92752192.0,3.301978e+07,0.153186,190573861.0,137441332.0,0.637621,1.704611e+08,0.790807,1.703565e+08,0.893913,21.01,10100.0,2003.0,585.0,87.0,431.0,40.0,13.0,14.0,6.0,200906.0,1.0,NaN,NaN
2,2,10100,2009,2006,703,106.0,15.078236,1,10100.0,463.0,4834.0,946.0,44.0,1687.0,NaN,NaN,502.0,4015.0,676.0,5.0,NaN,NaN,NaN,10100.0,21418880.0,83680866.0,9285758.0,92966624.0,109899299.0,21809847.0,224675770.0,0.372452,0.041330,0.413781,400060.0,2066613.0,58943059.0,6310445.0,4771588.0,5478167.0,104636.0,8201820.0,17248933.0,36382684.0,361152.0,10917401.0,4012540.0,18984955.0,12591807.0,35589302.0,3202637.0,2416650.0,192395147.0,6389009.0,9137435.0,7631707.0,215553298.0,0.099367,9122472.0,0.042321,10929.0,20557.761003,19723.057736,370462.0,114589.0,0.696095,0.694479,0.695287,92752192.0,3.301978e+07,0.153186,190573861.0,137441332.0,0.637621,1.704611e+08,0.790807,1.703565e+08,0.893913,21.01,10100.0,2005.0,718.0,152.0,350.0,36.0,6.0,174.0,4.0,200906.0,1.0,NaN,NaN
3,3,10100,2009,2006,703,106.0,15.078236,1,10100.0,463.0,4834.0,946.0,44.0,1687.0,NaN,NaN,502.0,4015.0,676.0,5.0,NaN,NaN,NaN,10100.0,21418880.0,83680866.0,9285758.0,92966624.0,109899299.0,21809847.0,224675770.0,0.372452,0.041330,0.413781,400060.0,2066613.0,58943059.0,6310445.0,4771588.0,5478167.0,104636.0,8201820.0,17248933.0,36382684.0,361152.0,10917401.0,4012540.0,18984955.0,12591807.0,35589302.0,3202637.0,2416650.0,192395147.0,6389009.0,9137435.0,7631707.0,215553298.0,0.099367,9122472.0,0.042321,10929.0,20557.761003,19723.057736,370462.0,114589.0,0.696095,0.694479,0.695287,92752192.0,3.301978e+07,0.153186,190573861.0,137441332.0,0.637621,1.704611e+08,0.790807,1.703565e+08,0.893913,21.01,10100.0,2005.0,718.0,152.0,379.0,36.0,6.0,145.0,4.8,200906.0,1.0,NaN,NaN
4,4,10100,2010,2007,766,83.0,10.835509,1,10100.0,539.0,4874.0,1009.0,37.0,1697.0,NaN,NaN,534.0,4275.0,628.0,72.0,NaN,NaN,NaN,10100.0,15586018.0,78024625.0,9583552.0,87608177.0,112564044.0,19445832.0,219618053.0,0.355274,0.043637,0.398912,479126.0,1842943.0,58529846.0,5805625.0,4490268.0,6077726.0,326886.0,7678209.0,16681345.0,41111625.0,63085.0,11040488.0,5768806.0,19033293.0,13574618.0,38376717.0,2607063.0,642815.0,195753767.0,6837068.0,8267608.0,7998064.0,218856507.0,0.071216,761546.0,0.003480,10805.0,20325.594910,20255.114021,413342.0,130510.0,0.692017,0.688707,0.690362,91584810.0,3.580966e+07,0.163622,195034066.0,140701530.0,0.642894,1.765112e+08,0.806516,1.761843e+08,0.903351,21.66,10100.0,2005.0,719.0,192.0,427.0,44.0,3.0,53.0,5.0,201006.0,1.0,NaN,NaN

(189851, 92)