In [1]:
import sys, subprocess
from io import StringIO
import pandas as pd
from importlib import reload

pd.set_option("display.max_rows", 999)
pd.set_option("display.max_columns", 999)
pd.set_option('display.max_rows', 999)
pd.set_option('display.min_rows', 999)

%config IPCompleter.use_jedi = False

In [2]:
df_combined = pd.read_pickle('../DataAll/df_combined_all.pkl')

In [3]:
display(df_combined.shape)
display(df_combined.head())
display(df_combined.dtypes)

(646324, 43)

,REPORT_SCHOOL_YEAR,AGGREGATION_INDEX,AGGREGATION_TYPE,AGGREGATION_CODE,AGGREGATION_NAME,ENTITY_INACTIVE_DATE,LEA_BEDS,LEA_NAME,NRC_CODE,NRC_DESC,COUNTY_CODE,COUNTY_NAME,NYC_IND,BOCES_CODE,BOCES_NAME,MEMBERSHIP_CODE,MEMBERSHIP_KEY,MEMBERSHIP_DESC,SUBGROUP_CODE,SUBGROUP_NAME,ENROLL_CNT,GRAD_CNT,GRAD_PCT,LOCAL_CNT,LOCAL_PCT,REG_CNT,REG_PCT,REG_ADV_CNT,REG_ADV_PCT,NON_DIPLOMA_CREDENTIAL_CNT,NON_DIPLOMA_CREDENTIAL_PCT,STILL_ENR_CNT,STILL_ENR_PCT,GED_CNT,GED_PCT,DROPOUT_CNT,DROPOUT_PCT,YEAR,NUM_TEACH,NUM_TEACH_INEXP,NUM_OUT_CERT,PER_TEACH_INEXP,PER_OUT_CERT
0,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,1,All Students,647,411,64%,56,9%,275,43%,80,12%,20,3%,30,5%,6,1%,180,28%,2015,1952.0,87.0,29.0,4.46,1.49
1,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,2,Female,307,207,67%,19,6%,150,49%,38,12%,9,3%,12,4%,0,0%,79,26%,2015,1952.0,87.0,29.0,4.46,1.49
2,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,3,Male,340,204,60%,37,11%,125,37%,42,12%,11,3%,18,5%,6,2%,101,30%,2015,1952.0,87.0,29.0,4.46,1.49
3,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,4,American Indian or Alaska Native,2,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2015,1952.0,87.0,29.0,4.46,1.49
4,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,5,Black or African American,348,200,57%,32,9%,156,45%,12,3%,16,5%,15,4%,6,2%,111,32%,2015,1952.0,87.0,29.0,4.46,1.49

REPORT_SCHOOL_YEAR             object
AGGREGATION_INDEX             float64
AGGREGATION_TYPE               object
AGGREGATION_CODE                int64
AGGREGATION_NAME               object
ENTITY_INACTIVE_DATE           object
LEA_BEDS                      float64
LEA_NAME                       object
NRC_CODE                      float64
NRC_DESC                       object
COUNTY_CODE                   float64
COUNTY_NAME                    object
NYC_IND                       float64
BOCES_CODE                    float64
BOCES_NAME                     object
MEMBERSHIP_CODE               float64
MEMBERSHIP_KEY                float64
MEMBERSHIP_DESC                object
SUBGROUP_CODE                   int64
SUBGROUP_NAME                  object
ENROLL_CNT                     object
GRAD_CNT                       object
GRAD_PCT                       object
LOCAL_CNT                      object
LOCAL_PCT                      object
REG_CNT                        object
REG_PCT                        object
REG_ADV_CNT                    object
REG_ADV_PCT                    object
NON_DIPLOMA_CREDENTIAL_CNT     object
NON_DIPLOMA_CREDENTIAL_PCT     object
STILL_ENR_CNT                  object
STILL_ENR_PCT                  object
GED_CNT                        object
GED_PCT                        object
DROPOUT_CNT                    object
DROPOUT_PCT                    object
YEAR                            int64
NUM_TEACH                     float64
NUM_TEACH_INEXP               float64
NUM_OUT_CERT                  float64
PER_TEACH_INEXP               float64
PER_OUT_CERT                  float64
dtype: object

In [4]:
df_grad = pd.read_pickle("../DataAll/df_grad_rate_all.pkl")
display(df_grad.shape)
display(df_grad.head())
display(df_grad.dtypes)

(674977, 38)

,REPORT_SCHOOL_YEAR,AGGREGATION_INDEX,AGGREGATION_TYPE,AGGREGATION_CODE,AGGREGATION_NAME,ENTITY_INACTIVE_DATE,LEA_BEDS,LEA_NAME,NRC_CODE,NRC_DESC,COUNTY_CODE,COUNTY_NAME,NYC_IND,BOCES_CODE,BOCES_NAME,MEMBERSHIP_CODE,MEMBERSHIP_KEY,MEMBERSHIP_DESC,SUBGROUP_CODE,SUBGROUP_NAME,ENROLL_CNT,GRAD_CNT,GRAD_PCT,LOCAL_CNT,LOCAL_PCT,REG_CNT,REG_PCT,REG_ADV_CNT,REG_ADV_PCT,NON_DIPLOMA_CREDENTIAL_CNT,NON_DIPLOMA_CREDENTIAL_PCT,STILL_ENR_CNT,STILL_ENR_PCT,GED_CNT,GED_PCT,DROPOUT_CNT,DROPOUT_PCT,YEAR
0,2014-15,0.0,Statewide,0,All Districts and Charters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,88.0,2009 Total Cohort - 6 Year Outcome,1,All Students,217658,180261,83%,11310,5%,101701,47%,67250,31%,3339,2%,7304,3%,2001,1%,24284,11%,2015
1,2014-15,0.0,Statewide,0,All Districts and Charters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,88.0,2009 Total Cohort - 6 Year Outcome,2,Female,106938,91548,86%,4749,4%,50328,47%,36471,34%,1186,1%,3020,3%,769,1%,10329,10%,2015
2,2014-15,0.0,Statewide,0,All Districts and Charters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,88.0,2009 Total Cohort - 6 Year Outcome,3,Male,110720,88713,80%,6561,6%,51373,46%,30779,28%,2153,2%,4284,4%,1232,1%,13955,13%,2015
3,2014-15,0.0,Statewide,0,All Districts and Charters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,88.0,2009 Total Cohort - 6 Year Outcome,4,American Indian or Alaska Native,1098,771,70%,80,7%,509,46%,182,17%,27,2%,40,4%,25,2%,231,21%,2015
4,2014-15,0.0,Statewide,0,All Districts and Charters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,88.0,2009 Total Cohort - 6 Year Outcome,5,Black or African American,40998,29940,73%,3044,7%,22964,56%,3932,10%,900,2%,2394,6%,476,1%,7080,17%,2015

REPORT_SCHOOL_YEAR             object
AGGREGATION_INDEX             float64
AGGREGATION_TYPE               object
AGGREGATION_CODE                int64
AGGREGATION_NAME               object
ENTITY_INACTIVE_DATE           object
LEA_BEDS                      float64
LEA_NAME                       object
NRC_CODE                      float64
NRC_DESC                       object
COUNTY_CODE                   float64
COUNTY_NAME                    object
NYC_IND                       float64
BOCES_CODE                    float64
BOCES_NAME                     object
MEMBERSHIP_CODE               float64
MEMBERSHIP_KEY                float64
MEMBERSHIP_DESC                object
SUBGROUP_CODE                   int64
SUBGROUP_NAME                  object
ENROLL_CNT                     object
GRAD_CNT                       object
GRAD_PCT                       object
LOCAL_CNT                      object
LOCAL_PCT                      object
REG_CNT                        object
REG_PCT                        object
REG_ADV_CNT                    object
REG_ADV_PCT                    object
NON_DIPLOMA_CREDENTIAL_CNT     object
NON_DIPLOMA_CREDENTIAL_PCT     object
STILL_ENR_CNT                  object
STILL_ENR_PCT                  object
GED_CNT                        object
GED_PCT                        object
DROPOUT_CNT                    object
DROPOUT_PCT                    object
YEAR                            int64
dtype: object

In [5]:
df_staff = pd.read_pickle("../DataAll/df_staff_qualifications_all.pkl")
display(df_staff.shape)
display(df_staff.head())
display(df_staff.dtypes)

(27686, 6)

,NUM_TEACH,NUM_TEACH_INEXP,NUM_OUT_CERT,YEAR,PER_TEACH_INEXP,PER_OUT_CERT
ENTITY_CD,,,,,,
10100010000,1952.0,87.0,29.0,2015,4.46,1.49
10100010014,66.0,0.0,0.0,2015,0.00,0.00
10100010016,76.0,8.0,0.0,2015,10.53,0.00
10100010018,93.0,6.0,5.0,2015,6.45,5.38
10100010019,108.0,2.0,0.0,2015,1.85,0.00

NUM_TEACH          float64
NUM_TEACH_INEXP    float64
NUM_OUT_CERT       float64
YEAR                 int64
PER_TEACH_INEXP    float64
PER_OUT_CERT       float64
dtype: object

## Aggregation Levels
I'm not sure we actually want to exclude the State, County, and NRC aggregation levels. Also it looks like there are about 1,000 schools missing from the combined data set.

In [6]:
df_combined.AGGREGATION_TYPE.value_counts()

School      423178
District    223146
Name: AGGREGATION_TYPE, dtype: int64

In [7]:
df_grad.AGGREGATION_TYPE.value_counts()

School                    424308
District                  223146
County                     24193
Need/Resource Category      2906
Statewide                    424
Name: AGGREGATION_TYPE, dtype: int64

In [8]:
df_grad.NRC_DESC.value_counts()

Average Needs                            223379
NYC                                      176448
Rural High Needs                          90863
Low Needs                                 86872
Urban-Suburban High Needs                 33644
Charters                                  20233
Buffalo, Rochester, Yonkers, Syracuse     18921
Name: NRC_DESC, dtype: int64

In [9]:
counties = df_grad[df_grad['AGGREGATION_TYPE'] == "District"].head()

In [10]:
df_grad[df_grad.AGGREGATION_NAME == "ALBANY CITY SCHOOL DISTRICT"].NRC_DESC.value_counts()

Urban-Suburban High Needs    410
Name: NRC_DESC, dtype: int64

In [11]:
df_grad[df_grad['AGGREGATION_TYPE'] == "District"].head()

,REPORT_SCHOOL_YEAR,AGGREGATION_INDEX,AGGREGATION_TYPE,AGGREGATION_CODE,AGGREGATION_NAME,ENTITY_INACTIVE_DATE,LEA_BEDS,LEA_NAME,NRC_CODE,NRC_DESC,COUNTY_CODE,COUNTY_NAME,NYC_IND,BOCES_CODE,BOCES_NAME,MEMBERSHIP_CODE,MEMBERSHIP_KEY,MEMBERSHIP_DESC,SUBGROUP_CODE,SUBGROUP_NAME,ENROLL_CNT,GRAD_CNT,GRAD_PCT,LOCAL_CNT,LOCAL_PCT,REG_CNT,REG_PCT,REG_ADV_CNT,REG_ADV_PCT,NON_DIPLOMA_CREDENTIAL_CNT,NON_DIPLOMA_CREDENTIAL_PCT,STILL_ENR_CNT,STILL_ENR_PCT,GED_CNT,GED_PCT,DROPOUT_CNT,DROPOUT_PCT,YEAR
4687,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,1,All Students,647,411,64%,56,9%,275,43%,80,12%,20,3%,30,5%,6,1%,180,28%,2015
4688,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,2,Female,307,207,67%,19,6%,150,49%,38,12%,9,3%,12,4%,0,0%,79,26%,2015
4689,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,3,Male,340,204,60%,37,11%,125,37%,42,12%,11,3%,18,5%,6,2%,101,30%,2015
4690,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,4,American Indian or Alaska Native,2,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2015
4691,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,5,Black or African American,348,200,57%,32,9%,156,45%,12,3%,16,5%,15,4%,6,2%,111,32%,2015

In [12]:
df_grad.groupby("AGGREGATION_TYPE").NRC_DESC.count()

AGGREGATION_TYPE
County                         0
District                  223146
Need/Resource Category      2906
School                    424308
Statewide                      0
Name: NRC_DESC, dtype: int64

In [13]:
df_grad.groupby("NRC_DESC").AGGREGATION_TYPE.count()

NRC_DESC
Average Needs                            223379
Buffalo, Rochester, Yonkers, Syracuse     18921
Charters                                  20233
Low Needs                                 86872
NYC                                      176448
Rural High Needs                          90863
Urban-Suburban High Needs                 33644
Name: AGGREGATION_TYPE, dtype: int64

In [14]:
df_grad.groupby("AGGREGATION_TYPE").GRAD_PCT.count()

AGGREGATION_TYPE
County                     24193
District                  223146
Need/Resource Category      2906
School                    424308
Statewide                    424
Name: GRAD_PCT, dtype: int64

# Grades 3-8 Exam Performance Levels

In [15]:
assessment_2019 = pd.read_csv("./3-8_ELA_AND_MATH_NYC_SUMMARY_2019.csv")

In [16]:
display(assessment_2019.shape)
display(assessment_2019.head())
display(assessment_2019.dtypes)

(7777, 17)

,SCHOOL YEAR END DATE,BEDS CODE,NAME,SUBJECT,STUDENT SUBGROUP,TOTAL TESTED,LEVEL 1 COUNT,LEVEL 1 PCT,LEVEL 2 COUNT,LEVEL 2 PCT,LEVEL 3 COUNT,LEVEL 3 PCT,LEVEL 4 COUNT,LEVEL 4 PCT,LEVEL 2-4 PCT,LEVEL 3-4 PCT,MEAN SCALE SCORE
0,06/30/2019,310100010000,NEW YORK CITY GEOGRAPHIC DISTRICT # 1,Grade 3 ELA,All Students,675,54,8%,207,31%,288,43%,126,19%,92%,61%,607
1,06/30/2019,310100010000,NEW YORK CITY GEOGRAPHIC DISTRICT # 1,Grade 3 Math,All Students,686,129,19%,139,20%,176,26%,242,35%,81%,61%,606
2,06/30/2019,310100010000,NEW YORK CITY GEOGRAPHIC DISTRICT # 1,Grade 4 ELA,All Students,678,104,15%,171,25%,217,32%,186,27%,85%,59%,605
3,06/30/2019,310100010000,NEW YORK CITY GEOGRAPHIC DISTRICT # 1,Grade 4 Math,All Students,678,170,25%,149,22%,122,18%,237,35%,75%,53%,604
4,06/30/2019,310100010000,NEW YORK CITY GEOGRAPHIC DISTRICT # 1,Grade 5 ELA,All Students,694,208,30%,184,27%,142,20%,160,23%,70%,44%,604

SCHOOL YEAR END DATE    object
BEDS CODE                int64
NAME                    object
SUBJECT                 object
STUDENT SUBGROUP        object
TOTAL TESTED            object
LEVEL 1 COUNT           object
LEVEL 1 PCT             object
LEVEL 2 COUNT           object
LEVEL 2 PCT             object
LEVEL 3 COUNT           object
LEVEL 3 PCT             object
LEVEL 4 COUNT           object
LEVEL 4 PCT             object
LEVEL 2-4 PCT           object
LEVEL 3-4 PCT           object
MEAN SCALE SCORE        object
dtype: object

In [17]:
df_grad.head()

,REPORT_SCHOOL_YEAR,AGGREGATION_INDEX,AGGREGATION_TYPE,AGGREGATION_CODE,AGGREGATION_NAME,ENTITY_INACTIVE_DATE,LEA_BEDS,LEA_NAME,NRC_CODE,NRC_DESC,COUNTY_CODE,COUNTY_NAME,NYC_IND,BOCES_CODE,BOCES_NAME,MEMBERSHIP_CODE,MEMBERSHIP_KEY,MEMBERSHIP_DESC,SUBGROUP_CODE,SUBGROUP_NAME,ENROLL_CNT,GRAD_CNT,GRAD_PCT,LOCAL_CNT,LOCAL_PCT,REG_CNT,REG_PCT,REG_ADV_CNT,REG_ADV_PCT,NON_DIPLOMA_CREDENTIAL_CNT,NON_DIPLOMA_CREDENTIAL_PCT,STILL_ENR_CNT,STILL_ENR_PCT,GED_CNT,GED_PCT,DROPOUT_CNT,DROPOUT_PCT,YEAR
0,2014-15,0.0,Statewide,0,All Districts and Charters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,88.0,2009 Total Cohort - 6 Year Outcome,1,All Students,217658,180261,83%,11310,5%,101701,47%,67250,31%,3339,2%,7304,3%,2001,1%,24284,11%,2015
1,2014-15,0.0,Statewide,0,All Districts and Charters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,88.0,2009 Total Cohort - 6 Year Outcome,2,Female,106938,91548,86%,4749,4%,50328,47%,36471,34%,1186,1%,3020,3%,769,1%,10329,10%,2015
2,2014-15,0.0,Statewide,0,All Districts and Charters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,88.0,2009 Total Cohort - 6 Year Outcome,3,Male,110720,88713,80%,6561,6%,51373,46%,30779,28%,2153,2%,4284,4%,1232,1%,13955,13%,2015
3,2014-15,0.0,Statewide,0,All Districts and Charters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,88.0,2009 Total Cohort - 6 Year Outcome,4,American Indian or Alaska Native,1098,771,70%,80,7%,509,46%,182,17%,27,2%,40,4%,25,2%,231,21%,2015
4,2014-15,0.0,Statewide,0,All Districts and Charters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,88.0,2009 Total Cohort - 6 Year Outcome,5,Black or African American,40998,29940,73%,3044,7%,22964,56%,3932,10%,900,2%,2394,6%,476,1%,7080,17%,2015

In [18]:
county = df_grad[df_grad.AGGREGATION_TYPE == 'County']
county.dtypes

REPORT_SCHOOL_YEAR             object
AGGREGATION_INDEX             float64
AGGREGATION_TYPE               object
AGGREGATION_CODE                int64
AGGREGATION_NAME               object
ENTITY_INACTIVE_DATE           object
LEA_BEDS                      float64
LEA_NAME                       object
NRC_CODE                      float64
NRC_DESC                       object
COUNTY_CODE                   float64
COUNTY_NAME                    object
NYC_IND                       float64
BOCES_CODE                    float64
BOCES_NAME                     object
MEMBERSHIP_CODE               float64
MEMBERSHIP_KEY                float64
MEMBERSHIP_DESC                object
SUBGROUP_CODE                   int64
SUBGROUP_NAME                  object
ENROLL_CNT                     object
GRAD_CNT                       object
GRAD_PCT                       object
LOCAL_CNT                      object
LOCAL_PCT                      object
REG_CNT                        object
REG_PCT                        object
REG_ADV_CNT                    object
REG_ADV_PCT                    object
NON_DIPLOMA_CREDENTIAL_CNT     object
NON_DIPLOMA_CREDENTIAL_PCT     object
STILL_ENR_CNT                  object
STILL_ENR_PCT                  object
GED_CNT                        object
GED_PCT                        object
DROPOUT_CNT                    object
DROPOUT_PCT                    object
YEAR                            int64
dtype: object

In [19]:
district = df_grad[df_grad.AGGREGATION_TYPE == 'District']
district.head()

,REPORT_SCHOOL_YEAR,AGGREGATION_INDEX,AGGREGATION_TYPE,AGGREGATION_CODE,AGGREGATION_NAME,ENTITY_INACTIVE_DATE,LEA_BEDS,LEA_NAME,NRC_CODE,NRC_DESC,COUNTY_CODE,COUNTY_NAME,NYC_IND,BOCES_CODE,BOCES_NAME,MEMBERSHIP_CODE,MEMBERSHIP_KEY,MEMBERSHIP_DESC,SUBGROUP_CODE,SUBGROUP_NAME,ENROLL_CNT,GRAD_CNT,GRAD_PCT,LOCAL_CNT,LOCAL_PCT,REG_CNT,REG_PCT,REG_ADV_CNT,REG_ADV_PCT,NON_DIPLOMA_CREDENTIAL_CNT,NON_DIPLOMA_CREDENTIAL_PCT,STILL_ENR_CNT,STILL_ENR_PCT,GED_CNT,GED_PCT,DROPOUT_CNT,DROPOUT_PCT,YEAR
4687,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,1,All Students,647,411,64%,56,9%,275,43%,80,12%,20,3%,30,5%,6,1%,180,28%,2015
4688,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,2,Female,307,207,67%,19,6%,150,49%,38,12%,9,3%,12,4%,0,0%,79,26%,2015
4689,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,3,Male,340,204,60%,37,11%,125,37%,42,12%,11,3%,18,5%,6,2%,101,30%,2015
4690,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,4,American Indian or Alaska Native,2,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2015
4691,2014-15,3.0,District,10100010000,ALBANY CITY SCHOOL DISTRICT,NaN,NaN,NaN,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,5,Black or African American,348,200,57%,32,9%,156,45%,12,3%,16,5%,15,4%,6,2%,111,32%,2015

In [20]:
agg_df = district.groupby(['REPORT_SCHOOL_YEAR', 'NRC_CODE', 'COUNTY_NAME', 'SUBGROUP_NAME'])

In [21]:
school = df_grad[(df_grad.AGGREGATION_TYPE == 'School') & (df_grad.SUBGROUP_CODE == 1)]

In [22]:
school.dtypes

REPORT_SCHOOL_YEAR             object
AGGREGATION_INDEX             float64
AGGREGATION_TYPE               object
AGGREGATION_CODE                int64
AGGREGATION_NAME               object
ENTITY_INACTIVE_DATE           object
LEA_BEDS                      float64
LEA_NAME                       object
NRC_CODE                      float64
NRC_DESC                       object
COUNTY_CODE                   float64
COUNTY_NAME                    object
NYC_IND                       float64
BOCES_CODE                    float64
BOCES_NAME                     object
MEMBERSHIP_CODE               float64
MEMBERSHIP_KEY                float64
MEMBERSHIP_DESC                object
SUBGROUP_CODE                   int64
SUBGROUP_NAME                  object
ENROLL_CNT                     object
GRAD_CNT                       object
GRAD_PCT                       object
LOCAL_CNT                      object
LOCAL_PCT                      object
REG_CNT                        object
REG_PCT                        object
REG_ADV_CNT                    object
REG_ADV_PCT                    object
NON_DIPLOMA_CREDENTIAL_CNT     object
NON_DIPLOMA_CREDENTIAL_PCT     object
STILL_ENR_CNT                  object
STILL_ENR_PCT                  object
GED_CNT                        object
GED_PCT                        object
DROPOUT_CNT                    object
DROPOUT_PCT                    object
YEAR                            int64
dtype: object

In [23]:
school.LEA_BEDS.astype('str').head(20)

42455    10100010000.0
42473    10100010000.0
42491    10100010000.0
42508    10100010000.0
42525    10100860907.0
42537    10100860907.0
42549    10100860907.0
42559    10100860907.0
42569    10100860960.0
42580    10100860960.0
42592    10100860960.0
42605    10100860960.0
42618    10201040000.0
42628    10201040000.0
42640    10201040000.0
42654    10201040000.0
42668    10306060000.0
42684    10306060000.0
42699    10306060000.0
42715    10306060000.0
Name: LEA_BEDS, dtype: object

In [32]:
school.head()

,REPORT_SCHOOL_YEAR,AGGREGATION_INDEX,AGGREGATION_TYPE,AGGREGATION_CODE,AGGREGATION_NAME,ENTITY_INACTIVE_DATE,LEA_BEDS,LEA_NAME,NRC_CODE,NRC_DESC,COUNTY_CODE,COUNTY_NAME,NYC_IND,BOCES_CODE,BOCES_NAME,MEMBERSHIP_CODE,MEMBERSHIP_KEY,MEMBERSHIP_DESC,SUBGROUP_CODE,SUBGROUP_NAME,ENROLL_CNT,GRAD_CNT,GRAD_PCT,LOCAL_CNT,LOCAL_PCT,REG_CNT,REG_PCT,REG_ADV_CNT,REG_ADV_PCT,NON_DIPLOMA_CREDENTIAL_CNT,NON_DIPLOMA_CREDENTIAL_PCT,STILL_ENR_CNT,STILL_ENR_PCT,GED_CNT,GED_PCT,DROPOUT_CNT,DROPOUT_PCT,YEAR
42455,2014-15,4.0,School,10100010034,ALBANY HIGH SCHOOL,NaN,1.010001e+10,ALBANY CITY SCHOOL DISTRICT,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,1,All Students,612,396,65%,41,7%,275,45%,80,13%,12,2%,28,5%,6,1%,170,28%,2015
42473,2014-15,4.0,School,10100010034,ALBANY HIGH SCHOOL,NaN,1.010001e+10,ALBANY CITY SCHOOL DISTRICT,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),8.0,89.0,2010 Total Cohort - 5 Year Outcome,1,All Students,561,323,58%,25,4%,235,42%,63,11%,7,1%,63,11%,4,1%,164,29%,2015
42491,2014-15,4.0,School,10100010034,ALBANY HIGH SCHOOL,NaN,1.010001e+10,ALBANY CITY SCHOOL DISTRICT,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),9.0,90.0,2011 Total Cohort - 4 Year Outcome,1,All Students,622,339,55%,18,3%,232,37%,89,14%,12,2%,146,23%,2,0%,123,20%,2015
42508,2014-15,4.0,School,10100010034,ALBANY HIGH SCHOOL,NaN,1.010001e+10,ALBANY CITY SCHOOL DISTRICT,3.0,Urban-Suburban High Needs,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),11.0,92.0,2011 Total Cohort - 4 Year Outcome - August 2015,1,All Students,622,365,59%,24,4%,252,41%,89,14%,12,2%,120,19%,2,0%,123,20%,2015
42525,2014-15,4.0,School,10100860907,GREEN TECH HIGH CHARTER SCHOOL,NaN,1.010086e+10,GREEN TECH HIGH CHARTER SCHOOL,7.0,Charters,1.0,ALBANY,0.0,190.0,ALBANY-SCHENECTADY-SCHOHARIE(CAPITAL REGION),6.0,88.0,2009 Total Cohort - 6 Year Outcome,1,All Students,53,46,87%,4,8%,25,47%,17,32%,0,0%,5,9%,0,0%,2,4%,2015

In [ ]:
county_crosswalk =

In [31]:
crossw

REPORT_SCHOOL_YEAR  AGGREGATION_INDEX  AGGREGATION_TYPE  AGGREGATION_CODE  AGGREGATION_NAME                                              ENTITY_INACTIVE_DATE  LEA_BEDS      LEA_NAME                                   NRC_CODE  NRC_DESC                               COUNTY_CODE  COUNTY_NAME  NYC_IND  BOCES_CODE  BOCES_NAME                 MEMBERSHIP_CODE  MEMBERSHIP_KEY  MEMBERSHIP_DESC                                   SUBGROUP_CODE  SUBGROUP_NAME  ENROLL_CNT  GRAD_CNT  GRAD_PCT  LOCAL_CNT  LOCAL_PCT  REG_CNT  REG_PCT  REG_ADV_CNT  REG_ADV_PCT  NON_DIPLOMA_CREDENTIAL_CNT  NON_DIPLOMA_CREDENTIAL_PCT  STILL_ENR_CNT  STILL_ENR_PCT  GED_CNT  GED_PCT  DROPOUT_CNT  DROPOUT_PCT  YEAR
2018-19             4.0                School            331800011589      ARTS AND MEDIA PREPARATORY ACADEMY                            06/30/17 00:00:00     3.318000e+11  NEW YORK CITY GEOGRAPHIC DISTRICT #18      1.0       NYC                                    33.0         KINGS        1.0      3090.0      NEW YORK CITY              18.0             146.0           2013 Total Cohort - 6 Year Outcome - August 2019  1              All Students   48          34        71%       2          4%         32       67%      0            0%           0                           0%                          6              13%            0        0%       8            17%          2019    1
2016-17             4.0                School            261701060009      NINTH GRADE ACADEMY                                           6/30/2017             2.617011e+11  RUSH-HENRIETTA CENTRAL SCHOOL DISTRICT     5.0       Average Needs                          26.0         MONROE       0.0      2691.0      MONROE 1                   8.0              113.0           2012 Total Cohort - 5 Year Outcome                1              All Students   -           -         -         -          -          -        -        -            -            -                           -                           -              -              -        -        -            -            2017    1
2014-15             4.0                School            320800011295      GATEWAY SCHOOL-ENVIR AND TECH                                 6/30/2015             3.208000e+11  NEW YORK CITY GEOGRAPHIC DISTRICT # 8      1.0       NYC                                    32.0         BRONX        1.0      3090.0      NEW YORK CITY              11.0             92.0            2011 Total Cohort - 4 Year Outcome - August 2015  1              All Students   39.0        19        49%       5          13%        14       36%      0            0%           0                           0%                          1              3%             1        3%       18           46%          2015    1
                                                         320800011650      JANE ADDAMS HS FOR ACADEMIC CAREERS                           6/30/2015             3.208000e+11  NEW YORK CITY GEOGRAPHIC DISTRICT # 8      1.0       NYC                                    32.0         BRONX        1.0      3090.0      NEW YORK CITY              6.0              88.0            2009 Total Cohort - 6 Year Outcome                1              All Students   192.0       102       53%       13         7%         88       46%      1            1%           8                           4%                          12             6%             6        3%       63           33%          2015    1
                                                                                                                                                                                                                                                                                                                                                   8.0              89.0            2010 Total Cohort - 5 Year Outcome                1              All Students   147.0       76        52%       9          6%         65       44%      2            1%           4                           3%                          8              5%             4        3%       55           37%          2015    1
                                                                                                                                                                                                                                                                                                                                                   9.0              90.0            2011 Total Cohort - 4 Year Outcome                1              All Students   87.0        48        55%       14         16%        34       39%      0            0%           7                           8%                          11             13%            0        0%       21           24%          2015    1
                                                                                                                                                                                                                                                                                                                                                   11.0             92.0            2011 Total Cohort - 4 Year Outcome - August 2015  1              All Students   87.0        48        55%       14         16%        34       39%      0            0%           7                           8%                          11             13%            0        0%       21           24%          2015    1
                                                         321000011660      GRACE DODGE CAREER AND TECH HS                                6/30/2015             3.210000e+11  NEW YORK CITY GEOGRAPHIC DISTRICT #10      1.0       NYC                                    32.0         BRONX        1.0      3090.0      NEW YORK CITY              6.0              88.0            2009 Total Cohort - 6 Year Outcome                1              All Students   291.0       137       47%       22         8%         113      39%      2            1%           6                           2%                          27             9%             6        2%       115          40%          2015    1
                                                                                                                                                                                                                                                                                                                                                   8.0              89.0            2010 Total Cohort - 5 Year Outcome                1              All Students   241.0       102       42%       16         7%         86       36%      0            0%           6                           2%                          22             9%             5        2%       106          44%          2015    1
                                                                                                                                                                                                                                                                                                                                                   9.0              90.0            2011 Total Cohort - 4 Year Outcome                1              All Students   104.0       53        51%       8          8%         45       43%      0            0%           7                           7%                          1              1%             2        2%       41           39%          2015    1
                                                                                                                                                                                                                                                                                                                                                   11.0             92.0            2011 Total Cohort - 4 Year Outcome - August 2015  1              All Students   104.0       53        51%       8          8%         45       43%      0            0%           7                           7%                          1              1%             2        2%       41           39%          2015    1
                                                         331700011544      INTERNATIONAL ARTS BUSINESS SCHOOL                            6/30/2015             3.317000e+11  NEW YORK CITY GEOGRAPHIC DISTRICT #17      1.0       NYC                                    33.0         KINGS        1.0      3090.0      NEW YORK CITY              6.0              88.0            2009 Total Cohort - 6 Year Outcome                1              All Students   80.0        63        79%       11         14%        52       65%      0            0%           1                           1%                          3              4%             1        1%       12           15%          2015    1
                                                                                                                                                                                                                                                                                                                                                   8.0              89.0            2010 Total Cohort - 5 Year Outcome                1              All Students   60.0        45        75%       5          8%         40       67%      0            0%           0                           0%                          1              2%             2        3%       11           18%          2015    1
                                                                                                                                                                                                                                                                                                                                                   9.0              90.0            2011 Total Cohort - 4 Year Outcome                1              All Students   17.0        12        71%       0          0%         12       71%      0            0%           0                           0%                          0              0%             0        0%       5            29%          2015    1
                                                                                                                                                                                                                                                                                                                                                   11.0             92.0            2011 Total Cohort - 4 Year Outcome - August 2015  1              All Students   17.0        12        71%       0          0%         12       71%      0            0%           0                           0%                          0              0%             0        0%       5            29%          2015    1
                                                         331900010166      JHS 166 GEORGE GERSHWIN                                       6/30/2015             3.319000e+11  NEW YORK CITY GEOGRAPHIC DISTRICT #19      1.0       NYC                                    33.0         KINGS        1.0      3090.0      NEW YORK CITY              9.0              90.0            2011 Total Cohort - 4 Year Outcome                1              All Students   1.0         -         -         -          -          -        -        -            -            -                           -                           -              -              -        -        -            -            2015    1
                                                                                                                                                                                                                                                                                                                                                   11.0             92.0            2011 Total Cohort - 4 Year Outcome - August 2015  1              All Students   1.0         -         -         -          -          -        -        -            -            -                           -                           -              -              -        -        -            -            2015    1
                                                         331900010302      JHS 302 RAFAEL CORDERO                                        6/30/2015             3.319000e+11  NEW YORK CITY GEOGRAPHIC DISTRICT #19      1.0       NYC                                    33.0         KINGS        1.0      3090.0      NEW YORK CITY              9.0              90.0            2011 Total Cohort - 4 Year Outcome                1              All Students   2.0         -         -         -          -          -        -        -            -            -                           -                           -              -              -        -        -            -            2015    1
                                                                                                                                                                                                                                                                                                                                                   11.0             92.0            2011 Total Cohort - 4 Year Outcome - August 2015  1              All Students   2.0         -         -         -          -          -        -        -            -            -                           -                           -              -              -        -        -            -            2015    1
2016-17             4.0                School            140600010099      BENNETT HIGH SCHOOL                                           6/30/2017             1.406000e+11  BUFFALO CITY SCHOOL DISTRICT               2.0       Buffalo, Rochester, Yonkers, Syracuse  14.0         ERIE         0.0      1491.0      ERIE 1                     6.0              112.0           2011 Total Cohort - 6 Year Outcome                1              All Students   179         105       59%       17         9%         88       49%      0            0%           1                           1%                          6              3%             5        3%       62           35%          2017    1
                                                                                                                                                                                                                                                                                                                                                   8.0              113.0           2012 Total Cohort - 5 Year Outcome                1              All Students   115         65        57%       13         11%        52       45%      0            0%           1                           1%                          4              3%             2        2%       42           37%          2017    1
                                                                                                                                                                                                                                                                                                                                                   9.0              114.0           2013 Total Cohort - 4 Year Outcome                1              All Students   87          45        52%       6          7%         39       45%      0            0%           2                           2%                          18             21%            0        0%       22           25%          2017    1
                                                                                                                                                                                                                                                                                                                                                   11.0             116.0           2013 Total Cohort - 4 Year Outcome - August 2017  1              All Students   87          49        56%       6          7%         43       49%      0            0%           2                           2%                          14             16%            0        0%       22           25%          2017    1
                                                         261600010060      CHARLOTTE HIGH SCHOOL                                         6/30/2017             2.616000e+11  ROCHESTER CITY SCHOOL DISTRICT             2.0       Buffalo, Rochester, Yonkers, Syracuse  26.0         MONROE       0.0      2691.0      MONROE 1                   6.0              112.0           2011 Total Cohort - 6 Year Outcome                1              All Students   135         73        54%       28         21%        41       30%      4            3%           0                           0%                          4              3%             0        0%       58           43%          2017    1
                                                                                                                                                                                                                                                                                                                                                   8.0              113.0           2012 Total Cohort - 5 Year Outcome                1              All Students   67          16        24%       7          10%        9        13%      0            0%           0                           0%                          1              1%             1        1%       49           73%          2017    1
                                                                                                                                                                                                                                                                                                                                                   9.0              114.0           2013 Total Cohort - 4 Year Outcome                1              All Students   36          6         17%       1          3%         4        11%      1            3%           0                           0%                          1              3%             0        0%       29           81%          2017    1
                                                                                                                                                                                                                                                                                                                                                   11.0             116.0           2013 Total Cohort - 4 Year Outcome - August 2017  1              All Students   36          6         17%       1          3%         4        11%      1            3%           0                           0%                          1              3%             0        0%       29           81%          2017    1